### ISSUE TITLE
Extract Pipeline can't be ran due to validation errors

### ISSUE THREAD

**Issue by tdashworth** [ewingjm/development-hub#73]
**Description**
Flow can no longer call the Extract pipeline because of: 
```json
{
  "status": 400,
  "message": "Could not queue the build because there were validation errors or warnings.\r\nAzure DevOps ActivityId: c6248c04-b903-4623-91d3-d22c10d86df1\r\nDetails: {\"ClassName\":\"Microsoft.TeamFoundation.Build.WebApi.BuildRequestValidationFailedException\",\"Message\":\"Could not queue the build because there were validation errors or warnings.\",\"Data\":null,\"InnerException\":null,\"HelpURL\":null,\"StackTraceString\":null,\"RemoteStackTraceString\":null,\"RemoteStackIndex\":0,\"ExceptionMethod\":null,\"HResult\":-2146232832,\"Source\":null,\"WatsonBuckets\":null,\"m_logException\":false,\"m_reportException\":false,\"m_errorCode\":0,\"m_logLevel\":\"warning\",\"m_eventId\":3000,\"ValidationResults\":[{\"result\":\"error\",\"message\":\"An error occurred while loading the YAML build pipeline. The repository Dynamics-Astro-FieldServices in project 98e11077-9170-4fcb-ac04-035a46bcbfa2 could not be retrieved. Verify the name and credentials being used.\"}]}\r\nclientRequestId: a3332d40-3706-4517-8d09-7cc846312509",
  "error": {
    "message": "Could not queue the build because there were validation errors or warnings.\r\nAzure DevOps ActivityId: c6248c04-b903-4623-91d3-d22c10d86df1\r\nDetails: {\"ClassName\":\"Microsoft.TeamFoundation.Build.WebApi.BuildRequestValidationFailedException\",\"Message\":\"Could not queue the build because there were validation errors or warnings.\",\"Data\":null,\"InnerException\":null,\"HelpURL\":null,\"StackTraceString\":null,\"RemoteStackTraceString\":null,\"RemoteStackIndex\":0,\"ExceptionMethod\":null,\"HResult\":-2146232832,\"Source\":null,\"WatsonBuckets\":null,\"m_logException\":false,\"m_reportException\":false,\"m_errorCode\":0,\"m_logLevel\":\"warning\",\"m_eventId\":3000,\"ValidationResults\":[{\"result\":\"error\",\"message\":\"An error occurred while loading the YAML build pipeline. The repository Dynamics-Astro-FieldServices in project 98e11077-9170-4fcb-ac04-035a46bcbfa2 could not be retrieved. Verify the name and credentials being used.\"}]}"
  },
  "source": "vsts-uks.azconn-uks-01.p.azurewebsites.net"
}
```
When trying to run the pipeline manually, I see the following:
![image](https://user-images.githubusercontent.com/9384593/116429288-a8005e80-a83d-11eb-8e37-cf50806ba9dd.png)

**Steps to reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
The extract pipeline should be able to run and called by the Flow.

**Environment (please complete the following information):**
![image](https://user-images.githubusercontent.com/9384593/116429477-d3834900-a83d-11eb-8dc3-7e7e57df573b.png)

**Additional context**
Extract pipeline YAML:
```yaml
name: 'Solution Merge'
pool:
  vmImage: windows-latest
trigger: none
steps:
  - checkout: self
    persistCredentials: true
  - task: PowerShell@2
    inputs:
      workingDirectory: $(Build.SourcesDirectory)
      filePath: 'pipelines/scripts/Merge-SolutionMerge.ps1'
      arguments: '-ClientId "$(clientId)" -TenantId "$(tenantId)" -ClientSecret (ConvertTo-SecureString "$(clientSecret)" -AsPlainText -Force) -SolutionMergeId "$(solutionMergeId)" -DevEnvironmentUrl "$(devEnvironmentUrl)"'
    displayName: Extract and commit
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
```
